spring:
 application:
   name: Hello World Service
message: The 'default' Profile Active
endpoints:
 enabled: true
 sensitive: false
logging:
 level:
   root: DEBUG
---
spring:
 profiles: dev
message: The 'dev' Environment Profile Active
logging:
 level:
   root: DEBUG
---
spring:
 profiles: test
message: The 'test' Environment Profile Active
logging:
 level:
   root: DEBUG
---
spring:
 profiles: prod
message: The 'prod' Environment Profile Active
endpoints:
 enabled: false
 health:
   enabled: true
 info:
   enabled: true
 sensitive: true
logging:
 level:
   root: WARN
